//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngContent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentEng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentEng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsPortal.App_GlobalResources_Folder.ContentEng", typeof(ContentEng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user didn&apos;t confirm Email..
        /// </summary>
        public static string AccountAuthentificationController_MessageAboutUnconfirmedMail {
            get {
                return ResourceManager.GetString("AccountAuthentificationController_MessageAboutUnconfirmedMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email not found or he didn&apos;t confirm email..
        /// </summary>
        public static string AccountController_ForgotPassword_ModelError {
            get {
                return ResourceManager.GetString("AccountController_ForgotPassword_ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions to reset your password are sent to your e-mail .
        /// </summary>
        public static string AccountController_ForgotPassword_ResetInstruction_Content {
            get {
                return ResourceManager.GetString("AccountController_ForgotPassword_ResetInstruction_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the link to reset password: .
        /// </summary>
        public static string AccountController_ForgotPassword_ResetLinkMessage {
            get {
                return ResourceManager.GetString("AccountController_ForgotPassword_ResetLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string AccountController_ForgotPassword_SendEmail_ResetPassword {
            get {
                return ResourceManager.GetString("AccountController_ForgotPassword_SendEmail_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something bad occured while processing your request..
        /// </summary>
        public static string AccountController_ResetPassword_MessaheAboutBadOccure {
            get {
                return ResourceManager.GetString("AccountController_ResetPassword_MessaheAboutBadOccure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You change your password!!!.
        /// </summary>
        public static string AccountController_ResetPassword_Report_Content {
            get {
                return ResourceManager.GetString("AccountController_ResetPassword_Report_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions to complete your registration are sent to your e-mail: .
        /// </summary>
        public static string AuthentificationController_ConfirmEmail_MessageAboutRegistrarionInstruction {
            get {
                return ResourceManager.GetString("AuthentificationController_ConfirmEmail_MessageAboutRegistrarionInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email doesn&apos;t exist..
        /// </summary>
        public static string AuthentificationController_ConfirmEmail_MessageAboutUnexistingMail {
            get {
                return ResourceManager.GetString("AuthentificationController_ConfirmEmail_MessageAboutUnexistingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user specified incorrect user&apos;s name..
        /// </summary>
        public static string AuthentificationController_Login_MessageAboutIncorrectName {
            get {
                return ResourceManager.GetString("AuthentificationController_Login_MessageAboutIncorrectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password provided is incorrect..
        /// </summary>
        public static string AuthentificationController_Login_MessageAboutIncorrectUserData {
            get {
                return ResourceManager.GetString("AuthentificationController_Login_MessageAboutIncorrectUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To complete the registration, click on the link: .
        /// </summary>
        public static string AuthentificationController_Register_EmailContent {
            get {
                return ResourceManager.GetString("AuthentificationController_Register_EmailContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions to complete your registration are sent to your e-mail .
        /// </summary>
        public static string AuthentificationController_Register_EmailInstructionToComplete {
            get {
                return ResourceManager.GetString("AuthentificationController_Register_EmailInstructionToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete registration.
        /// </summary>
        public static string AuthentificationController_Register_EmailLinkContent {
            get {
                return ResourceManager.GetString("AuthentificationController_Register_EmailLinkContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email.
        /// </summary>
        public static string AuthentificationController_Register_EmailSubject {
            get {
                return ResourceManager.GetString("AuthentificationController_Register_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incorrect content of comment..
        /// </summary>
        public static string CommentController_Create_ModelError {
            get {
                return ResourceManager.GetString("CommentController_Create_ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied..
        /// </summary>
        public static string CommentController_Delete_403 {
            get {
                return ResourceManager.GetString("CommentController_Delete_403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text of your comment:.
        /// </summary>
        public static string Create_Comments_View_CommentsContentLabel {
            get {
                return ResourceManager.GetString("Create_Comments_View_CommentsContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose image for news:.
        /// </summary>
        public static string Create_News_View_NewsItemChooseImgLabel {
            get {
                return ResourceManager.GetString("Create_News_View_NewsItemChooseImgLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create news.
        /// </summary>
        public static string Create_News_View_Title {
            get {
                return ResourceManager.GetString("Create_News_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit news.
        /// </summary>
        public static string Edit_View_Title {
            get {
                return ResourceManager.GetString("Edit_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword_View_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add news.
        /// </summary>
        public static string Index_View_AddNewsItem {
            get {
                return ResourceManager.GetString("Index_View_AddNewsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this news item?.
        /// </summary>
        public static string JS_ConfirmDeleteNewsItemMessage {
            get {
                return ResourceManager.GetString("JS_ConfirmDeleteNewsItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments..
        /// </summary>
        public static string ListOfComments_View_Title {
            get {
                return ResourceManager.GetString("ListOfComments_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Login_View_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_View_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_View_Title {
            get {
                return ResourceManager.GetString("Login_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your comment is too long.
        /// </summary>
        public static string Model_CommentInput_Text_Length {
            get {
                return ResourceManager.GetString("Model_CommentInput_Text_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a text of comment.
        /// </summary>
        public static string Model_CommentInput_Text_Required {
            get {
                return ResourceManager.GetString("Model_CommentInput_Text_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too big.
        /// </summary>
        public static string Model_NewsItemView_Picture_Size {
            get {
                return ResourceManager.GetString("Model_NewsItemView_Picture_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong image format.
        /// </summary>
        public static string Model_NewsItemView_Picture_Type {
            get {
                return ResourceManager.GetString("Model_NewsItemView_Picture_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the correct content for the news item.
        /// </summary>
        public static string Model_NewsItemView_Text_Required {
            get {
                return ResourceManager.GetString("Model_NewsItemView_Text_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the correct title for the news item.
        /// </summary>
        public static string Model_NewsItemView_Title_Required {
            get {
                return ResourceManager.GetString("Model_NewsItemView_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify your password (6 - 12 signs). It should contain at least one digit, one lower- and uppercase letter.
        /// </summary>
        public static string Model_Password {
            get {
                return ResourceManager.GetString("Model_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match.
        /// </summary>
        public static string Model_Password_Confirm {
            get {
                return ResourceManager.GetString("Model_Password_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify your Email.
        /// </summary>
        public static string Model_RegisterView_Email {
            get {
                return ResourceManager.GetString("Model_RegisterView_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length is 20.
        /// </summary>
        public static string Model_RegisterView_Login_Length {
            get {
                return ResourceManager.GetString("Model_RegisterView_Login_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify your login.
        /// </summary>
        public static string Model_RegisterView_Login_Required {
            get {
                return ResourceManager.GetString("Model_RegisterView_Login_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify your name.
        /// </summary>
        public static string Model_RegisterView_Name {
            get {
                return ResourceManager.GetString("Model_RegisterView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify your surname.
        /// </summary>
        public static string Model_RegisterView_Surname {
            get {
                return ResourceManager.GetString("Model_RegisterView_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data.
        /// </summary>
        public static string NewsController_Edit_ModelError {
            get {
                return ResourceManager.GetString("NewsController_Edit_ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add comments you need to be authenticated..
        /// </summary>
        public static string OpenNews_View_AddComments {
            get {
                return ResourceManager.GetString("OpenNews_View_AddComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview news.
        /// </summary>
        public static string PreviewNewsItem_View_Title {
            get {
                return ResourceManager.GetString("PreviewNewsItem_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_View_Title {
            get {
                return ResourceManager.GetString("Register_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword_View_Title {
            get {
                return ResourceManager.GetString("ResetPassword_View_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string View_BackToList {
            get {
                return ResourceManager.GetString("View_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to news list.
        /// </summary>
        public static string View_BackToNewsList {
            get {
                return ResourceManager.GetString("View_BackToNewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents: .
        /// </summary>
        public static string View_NewsItemContentLabel {
            get {
                return ResourceManager.GetString("View_NewsItemContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string View_Title {
            get {
                return ResourceManager.GetString("View_Title", resourceCulture);
            }
        }
    }
}
